In [20]:
import nltk
import numpy as np
import re
from nltk import punkt
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import OneHotEncoder

In [21]:
file1 = open("bag.txt","r")
text = file1.read()
print("The text is : ",text)
text = sent_tokenize(text)
i = 0
filteredText = []
visited = []
stop_words = set(stopwords.words('english'))
ps = PorterStemmer()

The text is :  I am eating orange icecream but I love chocolate icecream.


In [22]:
while(i<len(text)):
    tokens = word_tokenize(text[i])
    for token in tokens:
        if token not in (stop_words and visited) and token.isalpha():
            visited.append(token)
            filteredText.append(ps.stem(token))
        i += 1
print('PREPROCESSED: \n', filteredText)
doc = np.array(text).reshape(-1,1)
print("DOCUMENT: \n",doc)

vectorizer = CountVectorizer()
bow = vectorizer.fit_transform(text)
print("VOCABULARY:\n",vectorizer.get_feature_names_out())
print("\nBagOfWords:\n",bow.toarray())

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               

PREPROCESSED: 
 ['i', 'am', 'eat', 'orang', 'icecream', 'but', 'love', 'chocol']
DOCUMENT: 
 [['I am eating orange icecream but I love chocolate icecream.']]
VOCABULARY:
 ['am' 'but' 'chocolate' 'eating' 'icecream' 'love' 'orange']

BagOfWords:
 [[1 1 1 1 2 1 1]]


In [23]:
encoder = OneHotEncoder()
filteredText = np.array(filteredText).reshape(-1,1)
ohe = encoder.fit_transform(filteredText)
print("The One Hot Encoding : \n", ohe.toarray())

The One Hot Encoding : 
 [[0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]]
